# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 23:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Comments_app', '0003_auto_20170813_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
